# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

# Faster prompt for demos and workshops
command_timeout = 500

[character]
success_symbol = '[\$](bold green)'
error_symbol = '[\$](bold red)'

[nodejs]
symbol = "â¬¢ "
style = "bold green"

[python]
symbol = "ğŸ "
style = "bold yellow"

[golang]
symbol = "ğŸ¹ "
style = "bold cyan"

[rust]
symbol = "ğŸ¦€ "
style = "bold red"

[ruby]
symbol = "ğŸ”º "
style = "bold magenta"

[docker_context]
symbol = "ğŸ³ "
style = "bold blue"

[kubernetes]
disabled = false
